<ListCreator>:
    size_hint: (.8, .4)
    title: 'Create list'
    background_color: (0, 0, 0, 0)
    BoxLayout:
        orientation: 'vertical'
        size_hint: .8, 1
        Widget:
        CommonTextInput:
            id: listname
            color: (0, 0, 0, 1)
            text: 'Some list'
            on_focus:
                if self.focus: self.text = ''
        CommonButton:
            on_press: root.add_list(listname.text)
            text: 'Add'
        Widget: